version: '3'
services:
  app:
    image: laravelfans/laravel:8  # Usar la imagen existente
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel_network  

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdfinanzas
      MYSQL_USER: adminfinanciero
      MYSQL_PASSWORD: Finanzas1848
    ports:
      - "3306:3306"
    networks:
      - laravel_network  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - laravel_network  

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - laravel_network  

volumes:
  jenkins_home:

networks:
  laravel_network:       
