version: '3'
services:
  app:
    image: laravelfans/laravel:8 
    volumes:
      - .:/var/www/html
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=bdfinanzas
      - DB_USERNAME=adminfinanciero
      - DB_PASSWORD=Finanzas1848  
    networks:
      - laravel_network 
    working_dir: /var/www/html    
    

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdfinanzas
      MYSQL_USER: adminfinanciero
      MYSQL_PASSWORD: Finanzas1848
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    volumes:
      - mysql_data:/var/lib/mysql    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - laravel_network  

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - laravel_network  

volumes:
  jenkins_home:
  mysql_data:
  app_data:


networks:
  laravel_network:       
